language: go
go:
  - '1.9'
  - '1.10'
  - master
env:
  - ES_VERSION=5.3.3 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
  - ES_VERSION=6.0.1 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
matrix:
  allow_failures:
    - go: master
install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch -Epath.repo=/tmp &
  - export ELASTICSEARCH_URL=http://127.0.0.1:9200
  - export TF_LOG=INFO
  - go get github.com/mitchellh/gox
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout v0.13.1 && go install && cd -
  - glide install
script:
  - gox -os "freebsd darwin linux windows" -arch "386 amd64"
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - $ELASTICSEARCH_URL
  - TF_ACC=1 go test -v -cover
before_deploy: |
  # rename to match terraform provider conventions:
  #  https://www.terraform.io/docs/configuration/providers.html#third-party-plugins
  for file in terraform-provider-elasticsearch*; do mv "$file" "${file}_${TRAVIS_TAG}"; done
deploy:
  provider: releases
  api_key:
    secure: JOkdZIcFaAlf+RXY3xQ3MkTYxBCA5Ot2QOR7RtPTfbM1a7R9YrG0zFvgMNnZCiE5ONmf2OkJlcmSdviCE+awrBXSdARZXJFdO+CMa6Q9meyNYcQ8vBTM52BQLmkL2YF+mEEMnxgMD/qXyP4LXR45Hc0LamoDFiONx5w984VZRitPyNDoLczlH4uU3cecfWJN6GFCX/DyG4E1LSQFfy5jVoiaKTbWK/l+XeBJW2pyoCp9a/zmfsZsJhV6gr8Nl9PJxyu2dmgAHQKDEjjIJu6J1eP2vbC4YP/YI73RtWHMUGQ+yZpfd01dL6/NYpWwxZh4bKvtVk8CzHhikvD7DXQOc0yOxw52SMqct+ek0sfkRSz/l/AhwBbOobxbksUIUylBtTRIpH0elW//1WZ2+7pbcZB/SEeKecPoxpfyRQmV/VRRSoQWva9OQ3SObiypTLsPYCY9YG75vAkRddlASbtrErzLS3C8cbo4c7Hrl91Qxw/rNihYIFrwamSax7YJqyA6NmNqIMXr3H9BZMXy1H4FSXBnGOMmnmfeOw9WC4qU/KP31ieyOdzRvP18DQPQjggGz6fzdnIJ8mo1kT46vt9fK0h6AjGB+VVBt9BOBCO8dzPE8NASVE5uRV4FYsTMWOUKLO/SbmFdOpKHR8WIYOe8A7/sJMAnmZqocE8fykCwH9k=
  file: terraform-provider-elasticsearch*
  skip_cleanup: true
  file_glob: true
  on:
    tags: true
    branch: master
    go: '1.10'
